/**
 * The ciphera.net header/footer navigation, as plain data — the ONE canonical source for
 * both (a) the request-time SEED/fallback (`menu-runtime.ts`, used whenever 'menu' is off
 * or the CDN document is unreachable — i.e. always, this round) and (b) the mechanically
 * generated WordPress import seed (`scripts/generate-menus-seed.ts`).
 *
 * Design: Public/docs/plans/08-10-2026-web28-menus-footers-draft.md §4.2.2
 *
 * 🔑 NO REACT, NO NEXT IMPORT. `components/ui/header-3.tsx` and `components/Footer.tsx`
 * resolve an item's `media` key back to an actual icon component or image src with their
 * own small registries — kept out of this module so it stays importable from the
 * server-only runtime seam AND from a plain `tsx` script with nothing else loaded.
 *
 * 🔴 THIS MODULE IS THE SINGLE SOURCE OF THE CONTENT. There is no second copy of these
 * labels/hrefs/descriptions anywhere else in the two render components any more — moving
 * them here IS what "generated by a function from the existing arrays, not a hand copy"
 * means: the arrays themselves relocated, unchanged, and `buildHeaderMenuDocument()` /
 * `buildFooterMenuDocument()` are the functions that shape them into the document the CMS
 * will eventually hold.
 */
import type { MenuDocument, MenuItem } from './menu-build'

type SeedItem = MenuItem

const item = (label: string, href: string, description: string, media = ''): SeedItem => ({ label, href, description, media })

// ── Header (components/ui/header-3.tsx) ─────────────────────────────────────────────

export const HEADER_PRODUCT_ITEMS: SeedItem[] = [
  item('Pulse Analytics', '/products/pulse', 'Privacy-first web analytics', 'pulse-logo'),
  item('Ciphera Captcha', '/products/captcha', 'Privacy-respecting bot protection', 'captcha-logo'),
  item('Ciphera Relay', '/products/relay', 'Secure email infrastructure', 'relay-logo'),
  item('Tessera', '/products/tessera', 'Open-source OPAQUE auth library', 'lock'),
]

export const HEADER_COMPANY_ITEMS: SeedItem[] = [
  item('About Us', '/about', 'Our mission for a more private internet', 'users'),
  item('Sustainability', '/sustainability', 'Our carbon footprint, measured — see the real numbers', 'leaf'),
  item('Trust & Security', '/trust', 'Architecture proofs, warrant canary & disclosure policy', 'shield-check'),
  item('Press', '/press', 'Media kit, company facts & brand assets', 'newspaper'),
]

/** No description (the inventory's own words: "the last 2 ... have no description") — the
 * renderer places an item in the Company panel's second, description-less column exactly
 * when its description is empty, which is how these two stay visually distinct from
 * `HEADER_COMPANY_ITEMS` above without a separate "column" field in the document. */
export const HEADER_COMPANY_ITEMS_2: SeedItem[] = [
  item('Terms of Service', '/terms', '', 'file-text'),
  item('Privacy Policy', '/privacy', '', 'shield'),
]

export const HEADER_RESOURCES_ITEMS: SeedItem[] = [
  item('Blog', '/blog', 'Privacy & security insights', 'leaf'),
  item('Learn', '/learn', 'Guides & references for Ciphera products', 'book-open'),
  item('Glossary', '/glossary', 'Privacy & cryptography terms, defined precisely', 'file-text'),
  item('Ciphera ID', '/products/id', 'How signing in to Ciphera works', 'auth-logo'),
  item('Contact', '/contact', 'Get in touch with our team', 'mail'),
]

/** Every icon/image key the header's items reference — the publish-time validator's
 * `allowedMedia` set (§menu-build.ts). */
export const HEADER_MEDIA_KEYS: ReadonlySet<string> = new Set([
  'pulse-logo', 'captcha-logo', 'relay-logo', 'lock',
  'users', 'leaf', 'shield-check', 'newspaper', 'file-text', 'shield', 'book-open', 'auth-logo', 'mail',
])

/** The fixed hint row every header panel but Features carries (§4.2.2.1: "currently
 * identical fixed text, not authored content"). Only the link's TARGET is in the note;
 * the "Get in touch" label itself stays code (see the renderer). */
const HEADER_NOTE = { text: 'Interested?', href: '/contact' }

export function buildHeaderMenuDocument(): MenuDocument {
  return {
    location: 'header',
    groups: [
      { label: 'Products', source: 'manual', note: HEADER_NOTE, items: HEADER_PRODUCT_ITEMS },
      { label: 'Company', source: 'manual', note: HEADER_NOTE, items: [...HEADER_COMPANY_ITEMS, ...HEADER_COMPANY_ITEMS_2] },
      { label: 'Resources & Support', source: 'manual', note: HEADER_NOTE, items: HEADER_RESOURCES_ITEMS },
    ],
  }
}

// ── Footer (components/Footer.tsx) ──────────────────────────────────────────────────

export const FOOTER_PRODUCT_ITEMS: SeedItem[] = [
  item('Pulse Analytics', '/products/pulse', ''),
  item('Ciphera Captcha', '/products/captcha', ''),
  item('Ciphera Relay', '/products/relay', ''),
  item('Tessera', '/products/tessera', ''),
]

export const FOOTER_COMPANY_ITEMS: SeedItem[] = [
  item('About', '/about', ''),
  item('Contact', '/contact', ''),
  item('Press', '/press', ''),
  item('Sustainability', '/sustainability', ''),
]

export const FOOTER_RESOURCES_ITEMS: SeedItem[] = [
  item('Blog', '/blog', ''),
  item('Learn', '/learn', ''),
  item('Glossary', '/glossary', ''),
  item('Ciphera ID', '/products/id', ''),
  item('Help Center', 'https://help.ciphera.net', ''),
]

export const FOOTER_LEGAL_ITEMS: SeedItem[] = [
  item('Privacy Policy', '/privacy', ''),
  item('Terms of Service', '/terms', ''),
  item('Trust & Security', '/trust', ''),
]

/** The footer carries no icons on its items (§4.2.2.2: "no description/icon in the
 * footer") — kept as an explicit empty set so a stray `media` value is still caught and
 * repaired, rather than silently accepted because nothing was ever checked. */
export const FOOTER_MEDIA_KEYS: ReadonlySet<string> = new Set()

export function buildFooterMenuDocument(): MenuDocument {
  return {
    location: 'footer',
    brand: {
      name: 'Ciphera',
      blurb:
        'Privacy-first infrastructure and applications built on zero-knowledge principles. Your data is encrypted before it leaves your device.',
      social: [
        { icon: 'github', href: 'https://github.com/ciphera-net' },
        { icon: 'linkedin', href: 'https://www.linkedin.com/company/ciphera/' },
        { icon: 'x', href: 'https://x.com/CipheraNET' },
        { icon: 'discord', href: 'https://discord.gg/XRSkHCDD4x' },
      ],
    },
    groups: [
      { label: 'Products', source: 'manual', items: FOOTER_PRODUCT_ITEMS },
      { label: 'Company', source: 'manual', items: FOOTER_COMPANY_ITEMS },
      { label: 'Resources', source: 'manual', items: FOOTER_RESOURCES_ITEMS },
      { label: 'Legal', source: 'manual', items: FOOTER_LEGAL_ITEMS },
    ],
  }
}
